version: '3.1'

services:
  mongo:
    container_name: docker-mongo-banking
    image: mongo
    ports:
     - 27017:27017
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: banking
      MONGO_INITDB_ROOT_PASSWORD: banking
      MONGO_INITDB_DATABASE: banking

  mongo-express:
    container_name: mongo-express-banking
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: admin
      ME_CONFIG_MONGODB_URL: mongodb://banking:banking@mongo:27017/
